services:
  # Overrides the base app service with the devcontainer image
  app:
    image: mcr.microsoft.com/devcontainers/python:3.14
    volumes:
      - ../..:/workspaces:cached
      - ./daemon.json:/etc/docker/daemon.json
    #    network_mode: service:db
    command: sleep infinity
